

--select * from PROGRESS
--select * from STUDENT
--select * from [GROUP]
--select * from PROFESSION
--select * from FACULTY
--select * from SUBJECT
--select * from PULPIT

-- 3
use UNIVER
SELECT 
    FACULTY.FACULTY_NAME AS Faculty,
    PULPIT.PULPIT_NAME AS Pulpit,
    PROFESSION.PROFESSION_NAME AS Profession,
    SUBJECT.SUBJECT_NAME AS Subject,
    STUDENT.NAME AS StudentName,
    CASE 
        WHEN PROGRESS.NOTE = 6 THEN 'רוסעü'
        WHEN PROGRESS.NOTE = 7 THEN 'סולü'
        WHEN PROGRESS.NOTE = 8 THEN 'גמסולü'
    END AS Note
FROM 
    PROGRESS
INNER JOIN 
    STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN 
    [GROUP] ON STUDENT.IDGROUP = [GROUP].IDGROUP
INNER JOIN 
    PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION
INNER JOIN 
    FACULTY ON PROFESSION.FACULTY = FACULTY.FACULTY
INNER JOIN 
    SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN 
    PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
WHERE 
    PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY 
    PROGRESS.NOTE DESC;
