use master

select * from AUDITORIUM
select * from AUDITORIUM_TYPE

-- 6

SELECT 
    AUDITORIUM.AUDITORIUM AS AuditoriumCode,
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME AS AuditoriumTypeName
FROM 
    AUDITORIUM_TYPE
CROSS JOIN 
    AUDITORIUM;
Go

SELECT 
    AUDITORIUM.AUDITORIUM AS AuditoriumCode,
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME AS AuditoriumTypeName
FROM 
    AUDITORIUM_TYPE
CROSS JOIN 
    AUDITORIUM
WHERE 
    AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
