use UNIVER
SELECT AUDITORIUM, AUDITORIUM_CAPACITY
FROM AUDITORIUM a
WHERE AUDITORIUM_CAPACITY = (select top(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
order by AUDITORIUM_CAPACITY desc)