use UNIVER
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME,FACULTY.FACULTY
FROM FACULTY, PULPIT
WHERE FACULTY.FACULTY = PULPIT.FACULTY
and
FACULTY.FACULTY
In (Select FACULTY FROM PROFESSION
Where
(PROFESSION_NAME Like '%технологии%' OR PROFESSION_NAME Like '%технология%'	))

use UNIVER
Insert into PROFESSION(FACULTY,PROFESSION,PROFESSION_NAME,QUALIFICATION)
Values('Х004','F004','Мед-технология','техник')