use UNIVER
--2
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
FROM FACULTY 
Inner Join PULPIT
ON
FACULTY.FACULTY = PULPIT.FACULTY
WHERE
FACULTY.FACULTY In (Select FACULTY FROM PROFESSION
Where
(PROFESSION_NAME Like '%технологии%' OR PROFESSION_NAME Like '%технология%'))